# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bK2kDhVEvdj0Soi5wSGGbgkHoLw-DoB5
"""

import streamlit as st
import pandas as pd
from surprise import SVD, Dataset, Reader
from surprise.model_selection import train_test_split

# Load your dataset
df = pd.read_csv('final_ratings.csv')

reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(df[['User-ID', 'Book-Title', 'Book-Rating']], reader)
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

svd = SVD()
svd.fit(trainset)

st.title('Book Recommendation App')

# Input for Book Title
book_title = st.text_input('Enter Book Title', 'The Catcher in the Rye')

# Logic for getting recommendations
if st.button('Get Recommendations'):
    # Make predictions for the entered book title
    predictions = []
    for user_id in df['User-ID'].unique():
        pred = svd.predict(user_id, book_title)
        predictions.append({'User-ID': user_id, 'Prediction': pred.est})

    # Display top recommendations
    recommendations = pd.DataFrame(predictions).sort_values('Prediction', ascending=False)
    st.write(recommendations.head(10))