# -*- coding: utf-8 -*-
"""Book-title.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNrVfDSZIJDS02C3bn-8oEjcaZLc5IMU
"""

import pandas as pd
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split
import streamlit as st

# Load the dataset
file_path = "final_ratings.csv"
df = pd.read_csv(file_path)

# Create a Surprise Dataset
reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(df[['User-ID', 'ISBN', 'Book-Rating']], reader)

# Build the train set
trainset = data.build_full_trainset()

# Build the SVD model
svd_model = SVD()
svd_model.fit(trainset)

# Streamlit app
st.title("Book Recommendation App")

# Get book recommendations based on input book title
input_book_title = st.text_input("Enter a book title:", "The Da Vinci Code")  # Default book title for example

# Get book ISBN based on input book title
input_book_isbn = df[df['Book-Title'] == input_book_title]['ISBN'].values

if len(input_book_isbn) > 0:
    # Predict ratings for the input book
    input_book_ratings = [(trainset.to_inner_iid(isbn), svd_model.predict(trainset.to_inner_uid(6242), trainset.to_inner_iid(isbn)).est)
                          for isbn in input_book_isbn]

    # Sort predicted ratings in descending order
    input_book_ratings = sorted(input_book_ratings, key=lambda x: x[1], reverse=True)

    st.subheader("Top 5 Recommended Books:")

    # Display top 5 recommended books
    for i in range(min(5, len(input_book_ratings))):
        book_id, predicted_rating = input_book_ratings[i]
        book_title = df[df['ISBN'] == trainset.to_raw_iid(book_id)]['Book-Title'].values[0]
        book_author = df[df['ISBN'] == trainset.to_raw_iid(book_id)]['Book-Author'].values[0]
        st.write(f"{i + 1}. {book_title} by {book_author} (Predicted Rating: {predicted_rating:.2f})")

else:
    st.warning("Book not found. Please enter a valid book title.")